from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from io import BytesIO
from .models import ScanResult

def generate_pdf(result: ScanResult) -> bytes:
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # Header
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 50, "AuditAI Executive Summary")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 80, f"Target: {result.target}")
    c.drawString(50, height - 100, f"Date: {result.timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Score
    c.setFont("Helvetica-Bold", 48)
    c.setFillColor(colors.darkblue)
    c.drawString(width - 150, height - 80, f"{result.grade}")
    c.setFont("Helvetica", 12)
    c.drawString(width - 150, height - 100, f"Score: {result.score}/100")
    
    # Line
    c.setStrokeColor(colors.gray)
    c.line(50, height - 120, width - 50, height - 120)
    
    # Findings
    y = height - 160
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "Top Security Risks")
    y -= 30
    
    for finding in result.findings:
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, f"{finding.title} ({finding.severity})")
        y -= 20
        
        c.setFont("Helvetica", 10)
        c.setFillColor(colors.darkgray)
        c.drawString(50, y, f"Description: {finding.description}")
        y -= 15
        c.drawString(50, y, f"Recommendation: {finding.recommendation}")
        y -= 40
        
        if y < 100:
            c.showPage()
            y = height - 50

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.gray)
    c.drawString(50, 30, "Generated by AuditAI - Authorized Testing Only")
    
    c.save()
    buffer.seek(0)
    return buffer.getvalue()
